### ISSUE TITLE
Initial To Dos

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP24-NSP10_14-Frags#1]
OK @SharifahSabrina Great that this is started. Some things:

1) The "landing page" , i.e. [here](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags) - can you make this look like the other projects, i.e. all the essential operational info.
2) Fix up some typos in the wiki e.g. "fraglysis", Newmann etc.
3) Take out references that are listed traditionally and just link to the paper using DOIs. So instead of "Hu. B., Guo.H., Zhou. P., Shi. Z. L., Characteristics of SARS-CoV-2 and COVID-19, Nat Rev Microbiol, 2021, 19, 141–154" create a link to https://doi.org/10.1038/s41579-020-00459-7
4) Take out stuff to do with the origins of the project from the "story so far" and put into the origins page.
5) Incorporate the "The goal of our project" page into the "origins" page or the "story so far" - up to you, then delete the goals page.
6) "Rules" and "FAQ" - copy from another project
7) For "Selected fragments by Fraglysis and Binding interactions" page, try to think of a way to present the info in a way that takes up less space. But, crucially, we need (in your first Issue) the picture of the 18 overlapping fragments as per our discussions. The cluster of these fragments bound to the protein (to show where they are) and then the overlay of all the structures, showing the extent that they overlap. Then your second Issue is to take a pair and think about whether we can merge or link them, generating a new structure that we might be able to make.

Pinging @HadiaAmahli for info.

**Comment by mattodd** [comment]
Hi @HadiaAmahli @Sharifahsabrina hopefully we can meet up in the next week or so to clarify what we've learned and what are next steps. I'm very keen to finalise some designs that we think might be suitable for community synthesis. 

Before we close this issue, two things remain from the list above

1) Fix the FAQ page and
2) fix the "Selected fragments by Fraglysis and Binding interactions" page so it's a bit less cumbersome.

Ultimately, though, we still need a big, clear clustering diagram for the [Story So Far](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/wiki/The-Story-So-Far). One assumes we ought to be focussing on the biggest/deepest pocket on the interface. Where is that?

**Comment by HadiaAmahli** [comment]
Following our meeting yesterday 20th Feb 2024, two new issues have been created replying the existing issue (4), you can find all the details on issue [5](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/issues/5)
and issue [6](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/issues/6).

**Comment by HadiaAmahli** [comment]
Following our meeting yesterday 20th Feb 2024, two new issues have been created replying the existing issue (4), you can find all the details on issue [5](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/issues/5)
and issue [6](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/issues/6).
