### ISSUE TITLE
18 fragments - overlapping

### ISSUE THREAD

**Issue by Sharifahsabrina** [StructuralGenomicsConsortium/CNP24-NSP10_14-Frags#2]
An overlap between fragments 18, 15, 12, 11, 10, 8, and 3 can be observed at the NSP14 and NSP10 interface based on fragalysis. The cluster of these fragments bound to the NSP14 protein is seen in the images below. 

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/dce9743e-cb62-40f3-85c0-4c4c29c3ca35)
![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/4956652d-abda-4fec-9c95-392baff185a9)
![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/860e9d62-5efd-4f93-8c4d-e95dc9da1b00)
![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/016b6085-b1d0-4ec1-852d-be51963be0fa)

**Comment by mattodd** [comment]
Closing because this information is now in the wiki.
