### ISSUE TITLE
18 Fragments showed binding interactions to the interface of nsP10/14- Fraglysis

### ISSUE THREAD

**Issue by HadiaAmahli** [StructuralGenomicsConsortium/CNP24-NSP10_14-Frags#4]
Fraglysis helped us to know the structure of the 18 fragments that showed interaction to the nsP10/14, their structure is as following:

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/7b181d45-0d99-49b6-8479-85532d3dc379) 

The 18 fragments showed different clusters on the protein-protein interaction target, some of them are much bigger than others: 

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/9b8a3459-f62a-4bd6-9a6a-83ecba99c460)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/e8262092-f077-493c-ae6a-df2e76f99ab2)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/367163f8-95e7-4de4-b1e0-1e8a74832486)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/26c3a25c-961e-445f-b0dc-119c2e6548cd)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/6a2f1c3a-2e9d-41fb-bff0-e87d6a1ecb7b)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/1a4262e9-10ef-44ef-b9e0-a56a7a84dc30)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/427792fc-3374-413b-8e42-7e086a1f1dda)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/99d2a466-7f92-4891-ba77-b694adb4210a)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/d2c83236-ce46-4b78-832c-7c6a792792e3)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/30724f31-c4d7-4244-8fa2-63289bf589c3)

You can also see all these interactions by clicking this link: https://fragalysis.diamond.ac.uk/viewer/react/preview/target/NSP14/tas/lb18145-1

**Comment by mattodd** [comment]
Table taken from wiki and posted here for archiving: 
The overlay of all the structures were observed as the following table showing the overlapping between different fragments:

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/93838f75-1390-49e9-b308-e079bbaa780e)

Closing this issue as the information is essentially on the wiki.
