### ISSUE TITLE
The clusters of 18 fragments bound to the interface of NSP14

### ISSUE THREAD

**Issue by HadiaAmahli** [StructuralGenomicsConsortium/CNP24-NSP10_14-Frags#5]
There are 4 clusters of the [18 fragments](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/wiki/Selected-fragments-by-Fraglysis-and-Binding-interactions) that bound to the interface of NSP14 protein. These clusters exhibit binding at various sites within the NSP14/NSP10 interface. Four distinct clusters were formed due to the overlapping between specific fragments. 
1- In Cluster A, overlapping occurs between fragments 2 and 14. 
2- Cluster B highlights the overlapping areas between fragments 4, 9, and 17.
3- Cluster C is the biggest one as it has the largest pocket with significant overlapping, involving fragments 3, 8, 10, 11, 12, 15, and 16. 
4- Cluster D illustrates the overlapping between fragments 1 and 6.

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/133207721/23d820e6-b4f7-4afa-907b-5f98e273a298)

 We observed that fragments 5 and 7 do not exhibit any overlapping with other fragments. Consequently, fragments 5 and 7 will not be considered in the merging of fragments for the design of the new molecule.

**Comment by mattodd** [comment]
Closing, since this content is all now in the wiki.
